name: Mypy test

on:
  push

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip3 install mypy

    - name: Check library typing
      run: |
        mypy pyrule_compendium/__init__.py